### ISSUE TITLE
Add Install instructions

### ISSUE THREAD

**Issue by barraponto** [idlewan/link_cleaner#15]
How to install this extension?

**Comment by Atavic** [comment]
THe XPI [is here](https://addons.mozilla.org/en-US/firefox/addon/link-cleaner/).

**Comment by barraponto** [comment]
Thanks!
Maybe add it to the project description or README?

**Comment by idlewan** [comment]
Thanks for the suggestion, I've now added a link to the page on AMO at the top of the README.
