### ISSUE TITLE
Copying links to clipboard?

### ISSUE THREAD

**Issue by avdd** [idlewan/link_cleaner#25]
Seems not to work when copying links to the clipboard, on ubuntu at least.

**Comment by idlewan** [comment]
You have to visit the links for them to be intercepted and cleaned. You can then copy the url in the url bar.

The extension does not try to replicate CleanLinks or some other extension behavior of modifying the content of the page. I don't want to inject a script in every single page, try to find all links and clean them: this would be brittle and a lot more CPU-intensive + more memory used.

**Comment by avdd** [comment]
Kind of pointless then.  I use different browser profiles to sandbox facebook, and visiting links defeats that.

**Comment by idlewan** [comment]
It's not pointless, the browser actually never visits the links with the tracking params. The request is intercepted and modified to visit the links without tracking.
