### ISSUE TITLE
Redirects in v1.4 not working with current Nightly

### ISSUE THREAD

**Issue by scheinercc** [idlewan/link_cleaner#5]
Tested the sample links from AMO with 55.0a1 (2017-04-28) (64-bit) macOS and the parameters don't get removed atm.

**Comment by idlewan** [comment]
I'll check it out later this week, haven't had time yet.

**Comment by idlewan** [comment]
Can't reproduce on nightly 55.0a1 (2017-05-06) (64-bit) on Linux.

**Comment by scheinercc** [comment]
Re-tested and works for me again as well. Thanks for checking!
