### ISSUE TITLE
Reddit tracking issue

### ISSUE THREAD

**Issue by wolftune** [idlewan/link_cleaner#6]
So, I have currently CleanLinks, Link Cleaner 1.4, and uBlock Origin.

If I click links in Reddit (which look like direct when hovered but are actually tracking links), CleanLinks cleans them, end of story. If I turn CleanLinks off, then uBlock Origin stops the redirect and brings up a warning page asking if I am sure I want to visit the full tracking link, and if I say yes it will successfully track me.

Can Link Cleaner take care of this like CleanLinks does (so I can eventually drop CleanLinks)?

**Comment by idlewan** [comment]
There's a lot of links displayed in reddit pages, so I'm unsure what type of links you are seeing the uBlock tracking-blocked page with.
Do you have an example of page that displays those links for me to see ? I use uBlock Origin and don't have a filter activated that blocks the links I visit from reddit. 
Which url does uBlock displays to you on the choice page ?

Any reddit redirect link starting with `https://out.reddit.com/...` should be automatically converted to the right redirected url, without hitting a server (the addon intercepts the request and redirects it itself). There's thus no tracking that reddit can do this exact way, so no need for an interstitial page.

**Comment by wolftune** [comment]
I go to Reddit homeage, everything works with CleanLinks but does the yellow flash when clicking things. Turn off CleanLinks and stuff *within* Reddit works (but I'm not sure at this point without further investigation if Link Cleaner is stopping within-Reddit tracking, although CleanLinks seems to be doing so — of course, Reddit knows that I land on the resulting page, but shouldn't know what I clicked to get there). But stuff leaving Reddit gets caught by uBlock

```
uBlock Origin has prevented the following page from loading:

https://out.reddit.com/t3_6a042h?url=http%3A%2F%2Fi.imgur.com%2FgC16IZz.jpg&token=AQAATQoRWRg4tVfQ24WobWwOPTwggwwAFymrDmmKHvGKA0qknQE4&app_name=reddit.com

Because of the following filter

||out.reddit.com^
```

I'm guessing that somehow the uBlock plugin is getting to the link before Link Cleaner, so it's just an order of plugins issue. If Link Cleaner got to it first, then it would be cleaned. I could turn off that part of uBlock (I think), and then I'd guess that Link Cleaner would clean things, but *sometimes* that's not possible because the link is totally obscured, not part of the url, so I don't *want* to turn off any aspect of uBlock.

So, I think you're right about the problem, and if we assume that, maybe there's some way to solve this?

**Comment by idlewan** [comment]
>  [...] but sometimes that's not possible because the link is totally obscured, not part of the url, so I don't want to turn off any aspect of uBlock.

As far as the reddit external redirect goes, I'm not aware that the link is obscured. You could try to whitelist `out.reddit.com` in uBlock, this should do the trick (I don't know the specific syntax for the whitelist though).

Please be aware that this addon does not try to change the referer when you go to a url. If you're worrying about within-Reddit tracking, they probably log the referer (and maybe have other ways to track things).
Having an addon (especially a newer Webextension that would act like Smart Referer)  handle referer hiding is worthy in and of itself, but it's not the goal of this extension. I however would love to see one do that!

**Comment by Riamse** [comment]
For referrer spoofing you'd be looking for https://github.com/gorhill/uMatrix produced by the same author as uBlock Origin.

**Comment by wolftune** [comment]
@Riamse I tried uMatrix for a while, it seems like just an exceptionally manual next-level of uBlock's advanced mode. I might just try it again, but I am interested in the best automatic plugins that can protect people in general who won't do manual stuff.

**Comment by Riamse** [comment]
@wolftune That's true. That arises from the default setting of uMatrix, which is to allow everything first-party and third-party images+css, and disallow all other third-party requests. You can either disable matrix filtering, or remove the default filters and let all requests through, and enable the other privacy options (e.g. user agent spoofing, block hyperlink auditing), and uBlock will handle the blocking.

Of course it'd be nice if this was all automatic. Disabling matrix filtering globally is, fortunately, doable by changing the scope to * and hitting the power button.

**Comment by wolftune** [comment]
@Riamse I currently myself use uBlock with defaulting to blocking all 3rd-party…

**Comment by idlewan** [comment]
Closing since this can be fixed with a whitelist in uBlock.

The difference with CleanLinks as I understood it, is that CleanLinks modifies the links in the page (before clicking on them), so uBlock never captures them. With Link Cleaner, uBlock might capture the `out.reddit.com` before Link Cleaner, and might block it (depending on its filters) before it can be handled by Link Cleaner.
