### ISSUE TITLE
is this only limited to work on certain domains or to strip certain strings?

### ISSUE THREAD

**Issue by jawz101** [idlewan/link_cleaner#7]
I realize you're promoting this to be better than an outdated extension which does something similar but if it's just for cleaning links on a handful of domains or a few extra link cruft it's not that powerful.

**Comment by idlewan** [comment]
It cleans the utm_* parameters on all domains. If you know of some other generic rule that can be applied to all domains, I'm interested.

There is additionnally specific rules for some websites's pages, as you've seen, because they have redirect trackers or url parameters cruft. It's probably impossible to judge what is cruft on ALL domains with a generic rule, but it's still useful to clean specific websites.

**Comment by jawz101** [comment]
doesn't cleanlinks do a little more proactive monitoring?
"HTTP Observer to catch redirections. For example, this should make possible to clear links hidden behind shortened URLs."

**Comment by idlewan** [comment]
The Link Cleaner addon does not change links that appear on pages. It only cleans the url that the browser visits (the one that end up appearing in the url bar).

Other addons might rewrite links in the page that use a shortener, by hitting the shortened url, and then changing the href of the `<a>` link elements, but it's not the goal of this addon. I see now that the name I choose might be confusing (I used some time ago CleanLinks, and didn't know how to name this addon, so chose a name that felt right). It might be too late to change the name now though.

**Comment by idlewan** [comment]
I can't see CleanLinks description (since it was removed from AMO), but from the sentence you quoted here, it doesn't seem to prevent tracking for links hidden behind shortened URLs (which is difficult to solve anyway for this kind of links).

**Comment by jawz101** [comment]
Ah.  His add-on is on Github
https://github.com/diegocr/CleanLinks/commits/master?after=df438d1f68d5796aea93faa6aa4e5b29a3716b27+139

**Comment by Thorin-Oakenpants** [comment]
> It cleans the utm_* parameters on all domains. If you know of some other generic rule that can be applied to all domains, I'm interested.

I'll leave this in your capable hands. [Pure URL](https://addons.mozilla.org/firefox/addon/pure-url/) is a legacy addon that is now broken (53.02/54+). From the description:

> By default, Pure URL removes these garbage fields:
— utm_source, utm_medium, utm_term, utm_content, utm_campaign (spyware fields for the analytics.google.com)
— yclid (spyware fields for the metrika.yandex.ru)
— fb_action_ids, fb_action_types, fb_ref, fb_source, action_object_map, action_type_map, action_ref_map (spyware fields from the facebook.com)

and from the installed add-on's options page, the editable "garbage" field held this:
```
utm_source, utm_medium, utm_term, utm_content, utm_campaign, utm_reader, utm_place, ga_source, ga_medium, ga_term, ga_content, ga_campaign, ga_place, yclid, _openstat, fb_action_ids, fb_action_types, fb_ref, fb_source, action_object_map, action_type_map, action_ref_map
```

You already seem to have `utm_*` covered (and on all urls), and some facebook was covered in #1. So the above info is just that, for your info / consideration. I do not know if the above was applied to all domains or limited to the domains as per the description (personally I don't even use facebook or yandex).

PS: Thanks for the extension - you're on [list](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-B:-Firefox-Add-ons#small_orange_diamond-recommended-web-extensions)

**Comment by vctls** [comment]
A challenger appears!
https://addons.mozilla.org/fr/firefox/addon/neat-url/
